"""create core multi-tenant schema

Revision ID: 2becd68d611b
Revises: 
Create Date: 2026-08-17 16:41:27.808913
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2becd68d611b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_user_action_timestamp', 'audit_logs', ['user_id', 'action', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_workspace_action_timestamp', 'audit_logs', ['workspace_id', 'action', 'created_at'], unique=False)
    op.create_table('provider_webhook_events',
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('external_event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_webhook_events_provider'), 'provider_webhook_events', ['provider'], unique=False)
    op.create_index(op.f('ix_provider_webhook_events_status'), 'provider_webhook_events', ['status'], unique=False)
    op.create_index('uq_provider_webhook_event_provider_external', 'provider_webhook_events', ['provider', 'external_event_id'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_admin'), 'users', ['is_admin'], unique=False)
    op.create_table('workspaces',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('workspace_type', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('billing_accounts',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('external_customer_id', sa.String(length=255), nullable=True),
    sa.Column('plan_code', sa.String(length=80), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_accounts_external_customer_id'), 'billing_accounts', ['external_customer_id'], unique=False)
    op.create_index(op.f('ix_billing_accounts_plan_code'), 'billing_accounts', ['plan_code'], unique=False)
    op.create_index(op.f('ix_billing_accounts_source'), 'billing_accounts', ['source'], unique=False)
    op.create_index(op.f('ix_billing_accounts_workspace_id'), 'billing_accounts', ['workspace_id'], unique=False)
    op.create_table('projects',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=False),
    sa.Column('brand_aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('target_country', sa.String(length=10), nullable=True),
    sa.Column('target_language', sa.String(length=10), nullable=True),
    sa.Column('target_audience', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_scan_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_domain'), 'projects', ['domain'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_index(op.f('ix_projects_workspace_id'), 'projects', ['workspace_id'], unique=False)
    op.create_table('workspace_members',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'user_id', name='uq_workspace_member_workspace_user')
    )
    op.create_index(op.f('ix_workspace_members_user_id'), 'workspace_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_members_workspace_id'), 'workspace_members', ['workspace_id'], unique=False)
    op.create_table('appsumo_licenses',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('billing_account_id', sa.UUID(), nullable=True),
    sa.Column('external_license_id', sa.String(length=255), nullable=False),
    sa.Column('appsumo_plan', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['billing_account_id'], ['billing_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appsumo_licenses_billing_account_id'), 'appsumo_licenses', ['billing_account_id'], unique=False)
    op.create_index(op.f('ix_appsumo_licenses_external_license_id'), 'appsumo_licenses', ['external_license_id'], unique=False)
    op.create_index(op.f('ix_appsumo_licenses_status'), 'appsumo_licenses', ['status'], unique=False)
    op.create_index(op.f('ix_appsumo_licenses_workspace_id'), 'appsumo_licenses', ['workspace_id'], unique=False)
    op.create_table('competitors',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'domain', name='uq_competitor_project_domain')
    )
    op.create_index(op.f('ix_competitors_project_id'), 'competitors', ['project_id'], unique=False)
    op.create_table('project_keywords',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('intent', sa.String(length=255), nullable=True),
    sa.Column('funnel_stage', sa.String(length=20), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'text', name='uq_project_keyword_project_text')
    )
    op.create_index(op.f('ix_project_keywords_project_id'), 'project_keywords', ['project_id'], unique=False)
    op.create_table('project_providers',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'provider', name='uq_project_provider_project_provider')
    )
    op.create_index(op.f('ix_project_providers_project_id'), 'project_providers', ['project_id'], unique=False)
    op.create_table('usage_events',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('ai_checks', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.DECIMAL(precision=12, scale=6), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_events_event_type'), 'usage_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_usage_events_project_id'), 'usage_events', ['project_id'], unique=False)
    op.create_index(op.f('ix_usage_events_user_id'), 'usage_events', ['user_id'], unique=False)
    op.create_index(op.f('ix_usage_events_workspace_id'), 'usage_events', ['workspace_id'], unique=False)
    op.create_table('prompts',
    sa.Column('project_keyword_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(length=1000), nullable=False),
    sa.Column('prompt_set_version', sa.Integer(), nullable=False),
    sa.Column('prompt_type', sa.String(length=20), nullable=False),
    sa.Column('intent', sa.String(length=255), nullable=True),
    sa.Column('funnel_stage', sa.String(length=20), nullable=True),
    sa.Column('persona', sa.String(length=255), nullable=True),
    sa.Column('target_country', sa.String(length=10), nullable=True),
    sa.Column('target_language', sa.String(length=10), nullable=True),
    sa.Column('commercial_intent', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_keyword_id'], ['project_keywords.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompts_project_keyword_id'), 'prompts', ['project_keyword_id'], unique=False)
    op.create_index(op.f('ix_prompts_prompt_set_version'), 'prompts', ['prompt_set_version'], unique=False)
    op.create_index(op.f('ix_prompts_prompt_type'), 'prompts', ['prompt_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompts_prompt_type'), table_name='prompts')
    op.drop_index(op.f('ix_prompts_prompt_set_version'), table_name='prompts')
    op.drop_index(op.f('ix_prompts_project_keyword_id'), table_name='prompts')
    op.drop_table('prompts')
    op.drop_index(op.f('ix_usage_events_workspace_id'), table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_user_id'), table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_project_id'), table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_event_type'), table_name='usage_events')
    op.drop_table('usage_events')
    op.drop_index(op.f('ix_project_providers_project_id'), table_name='project_providers')
    op.drop_table('project_providers')
    op.drop_index(op.f('ix_project_keywords_project_id'), table_name='project_keywords')
    op.drop_table('project_keywords')
    op.drop_index(op.f('ix_competitors_project_id'), table_name='competitors')
    op.drop_table('competitors')
    op.drop_index(op.f('ix_appsumo_licenses_workspace_id'), table_name='appsumo_licenses')
    op.drop_index(op.f('ix_appsumo_licenses_status'), table_name='appsumo_licenses')
    op.drop_index(op.f('ix_appsumo_licenses_external_license_id'), table_name='appsumo_licenses')
    op.drop_index(op.f('ix_appsumo_licenses_billing_account_id'), table_name='appsumo_licenses')
    op.drop_table('appsumo_licenses')
    op.drop_index(op.f('ix_workspace_members_workspace_id'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_user_id'), table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index(op.f('ix_projects_workspace_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_domain'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_billing_accounts_workspace_id'), table_name='billing_accounts')
    op.drop_index(op.f('ix_billing_accounts_source'), table_name='billing_accounts')
    op.drop_index(op.f('ix_billing_accounts_plan_code'), table_name='billing_accounts')
    op.drop_index(op.f('ix_billing_accounts_external_customer_id'), table_name='billing_accounts')
    op.drop_table('billing_accounts')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_users_is_admin'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('uq_provider_webhook_event_provider_external', table_name='provider_webhook_events')
    op.drop_index(op.f('ix_provider_webhook_events_status'), table_name='provider_webhook_events')
    op.drop_index(op.f('ix_provider_webhook_events_provider'), table_name='provider_webhook_events')
    op.drop_table('provider_webhook_events')
    op.drop_index('ix_audit_logs_workspace_action_timestamp', table_name='audit_logs')
    op.drop_index('ix_audit_logs_user_action_timestamp', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
