"""Provider domain objects — immutable typed structures for provider I/O.

These objects are the contract between provider adapters and the rest of
the system. They are deliberately decoupled from:
- FastAPI routers (adapters are infrastructure/domain services)
- SQLAlchemy (adapters do not persist anything)
- Quota/usage accounting (Phase 6 Scan Engine owns that)

All objects are frozen (immutable) to prevent later stages from
accidentally mutating evidence returned by the adapter.
"""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass, field
from typing import Protocol, runtime_checkable

from app.core.enums import LLMProvider, ProviderExecutionMode, ProviderSurface


@dataclass(frozen=True)
class ProviderRequest:
    """Immutable request to a provider adapter.

    The prompt text sent to the provider must remain EXACTLY the
    Prompt.text generated by the PromptSet. Adapters must NOT
    automatically prepend provider-specific SEO instructions, system
    prompts, or few-shot examples. This preserves cross-provider
    measurement comparability.
    """

    prompt: str
    mode: ProviderExecutionMode
    model: str | None = None
    target_country: str | None = None
    target_language: str | None = None
    max_output_tokens: int | None = None
    correlation_id: str | None = None


@dataclass(frozen=True)
class ProviderCitation:
    """A single citation/source returned by the provider.

    Normalized from each provider's native citation format.
    Do not invent a citation when the provider did not return one.
    """

    url: str
    title: str | None = None
    source_type: str | None = None
    start_index: int | None = None
    end_index: int | None = None
    cited_text: str | None = None


@dataclass(frozen=True)
class ProviderUsage:
    """Normalized token/usage information from a provider response.

    None means the provider did not report this field.
    0 means the provider explicitly reported zero.
    Do NOT convert missing usage to fake zero.
    """

    input_tokens: int | None = None
    output_tokens: int | None = None
    total_tokens: int | None = None
    cached_input_tokens: int | None = None
    cache_write_input_tokens: int | None = None
    reasoning_tokens: int | None = None
    search_requests: int | None = None


@dataclass(frozen=True)
class ProviderCapabilities:
    """Declares what a provider adapter supports.

    The registry exposes this WITHOUT performing any API call.
    """

    supports_model_only: bool
    supports_web_grounded: bool
    supports_citations: bool
    supports_search_result_metadata: bool


@dataclass(frozen=True)
class ProviderResult:
    """Immutable normalized result from a provider execution.

    This is the evidence object. It must not be mutated after creation.

    IMPORTANT:
    - provider_request_id is the ID assigned by the provider (e.g.
      OpenAI response ID, Anthropic message ID). It is distinct from
      our internal correlation_id.
    - metadata must NOT contain API keys, Authorization headers, or
      raw response bodies.
    - response_text must NOT be empty for a nominally successful
      response (ProviderResponseError is raised otherwise).
    """

    provider: LLMProvider
    surface: ProviderSurface
    execution_mode: ProviderExecutionMode
    requested_model: str
    returned_model: str | None
    response_text: str
    citations: tuple[ProviderCitation, ...]
    usage: ProviderUsage
    provider_request_id: str | None
    finish_reason: str | None
    latency_ms: int
    search_used: bool
    metadata: Mapping[str, str | int | float | bool | None] = field(default_factory=dict)


@runtime_checkable
class ProviderAdapter(Protocol):
    """Protocol for provider adapters.

    Adapters are async infrastructure services. They:
    - Execute exactly ONE provider request per execute() call
    - Do NOT automatically retry
    - Do NOT call quota/usage services
    - Do NOT persist anything
    - Do NOT couple to FastAPI or SQLAlchemy
    """

    provider: LLMProvider
    surface: ProviderSurface

    def capabilities(self) -> ProviderCapabilities: ...

    async def execute(self, request: ProviderRequest) -> ProviderResult: ...
