"""Provider domain objects — immutable typed structures for provider I/O.

These objects are the contract between provider adapters and the rest of
the system. They are deliberately decoupled from:
- FastAPI routers (adapters are infrastructure/domain services)
- SQLAlchemy (adapters do not persist anything)
- Quota/usage accounting (Phase 6 Scan Engine owns that)

All objects are frozen (immutable) to prevent later stages from
accidentally mutating evidence returned by the adapter.
"""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass, field
from decimal import Decimal
from typing import Protocol, runtime_checkable

from app.core.enums import LLMProvider, ProviderExecutionMode, ProviderSurface


@dataclass(frozen=True)
class ProviderRequest:
    """Immutable request to a provider adapter.

    The prompt text sent to the provider must remain EXACTLY the
    Prompt.text generated by the PromptSet. Adapters must NOT
    automatically prepend provider-specific SEO instructions, system
    prompts, or few-shot examples. This preserves cross-provider
    measurement comparability.
    """

    prompt: str
    mode: ProviderExecutionMode
    model: str | None = None
    target_country: str | None = None
    target_language: str | None = None
    max_output_tokens: int | None = None
    correlation_id: str | None = None


@dataclass(frozen=True)
class ProviderCitation:
    """A single citation/source returned by the provider.

    Normalized from each provider's native citation format.
    Do not invent a citation when the provider did not return one.
    """

    url: str
    title: str | None = None
    source_type: str | None = None
    start_index: int | None = None
    end_index: int | None = None
    cited_text: str | None = None


@dataclass(frozen=True)
class ProviderUsage:
    """Normalized token/usage information from a provider response.

    None means the provider did not report this field.
    0 means the provider explicitly reported zero.
    Do NOT convert missing usage to fake zero.

    Web tool counters (additive, backward-compatible):

    - search_requests: LEGACY provider-native counter.  For OpenAI this is
      the TOTAL number of ``web_search_call`` output items (all action
      types).  For Anthropic/Perplexity it is the provider-reported search
      count.  DEPRECATED as a billing authority — kept only for
      compatibility with historical rows.  New economic code MUST NOT use
      this field for pricing.
    - web_tool_call_count: total OpenAI ``web_search_call`` output items,
      regardless of ``action.type``.  This is the authority for the
      ``max_tool_calls`` bound check (the OpenAI bound applies to TOTAL
      built-in tool calls processed).  None when the provider does not
      expose a per-item breakdown.
    - search_action_count: number of ``web_search_call`` items whose
      ``action.type == "search"``.  This is the ONLY documented billable
      web-search counter and is the authority for the search tariff.
      For Anthropic/Perplexity this mirrors the provider-reported search
      count.
    - open_page_action_count: ``action.type == "open_page"``.
    - find_in_page_action_count: ``action.type == "find_in_page"``.
    - unknown_web_action_count: ``action`` missing or unrecognized type.
      Counts toward the tool bound but is NEVER assumed billable or free;
      any non-zero value makes local cost calculation fail-closed.

    Invariant (when web_tool_call_count is not None):
        web_tool_call_count == search_action_count
                               + open_page_action_count
                               + find_in_page_action_count
                               + unknown_web_action_count
    """

    input_tokens: int | None = None
    output_tokens: int | None = None
    total_tokens: int | None = None
    cached_input_tokens: int | None = None
    cache_write_input_tokens: int | None = None
    reasoning_tokens: int | None = None
    citation_tokens: int | None = None
    search_requests: int | None = None
    web_tool_call_count: int | None = None
    search_action_count: int | None = None
    open_page_action_count: int | None = None
    find_in_page_action_count: int | None = None
    unknown_web_action_count: int | None = None

    def __post_init__(self) -> None:
        if self.web_tool_call_count is None:
            return
        parts = (
            self.search_action_count,
            self.open_page_action_count,
            self.find_in_page_action_count,
            self.unknown_web_action_count,
        )
        if any(p is None for p in parts):
            raise ValueError(
                "ProviderUsage: web_tool_call_count requires all four action counters."
            )
        total = sum(p for p in parts if p is not None)
        if total != self.web_tool_call_count:
            raise ValueError(
                "ProviderUsage: web_tool_call_count must equal the sum of action counters "
                f"(total={self.web_tool_call_count}, sum={total})."
            )


@dataclass(frozen=True)
class ProviderCapabilities:
    """Declares what a provider adapter supports.

    The registry exposes this WITHOUT performing any API call.
    """

    supports_model_only: bool
    supports_web_grounded: bool
    supports_citations: bool
    supports_search_result_metadata: bool


@dataclass(frozen=True)
class ProviderResult:
    """Immutable normalized result from a provider execution.

    This is the evidence object. It must not be mutated after creation.

    IMPORTANT:
    - provider_request_id is the HTTP request/support identifier returned
      by the provider (e.g. OpenAI x-request-id, Anthropic request-id header).
      It is NOT the generated resource/object ID.
    - provider_response_id is the generated resource/object identifier
      (e.g. OpenAI response ID, Anthropic message ID, Google interaction ID,
      Perplexity completion ID). Distinct from the HTTP request ID.
    - provider_reported_cost_usd is the cost reported by the provider itself
      (not our own pricing calculation). Uses Decimal for money safety.
    - metadata must NOT contain API keys, Authorization headers, or
      raw response bodies.
    - response_text must NOT be empty for a nominally successful
      response (ProviderResponseError is raised otherwise).
    """

    provider: LLMProvider
    surface: ProviderSurface
    execution_mode: ProviderExecutionMode
    requested_model: str
    returned_model: str | None
    response_text: str
    citations: tuple[ProviderCitation, ...]
    usage: ProviderUsage
    provider_request_id: str | None
    provider_response_id: str | None
    finish_reason: str | None
    latency_ms: int
    search_used: bool
    provider_reported_cost_usd: Decimal | None = None
    metadata: Mapping[str, str | int | float | bool | None] = field(default_factory=dict)


@dataclass(frozen=True)
class ProviderFailureEvidence:
    """Evidence from a provider response that was received (HTTP 200 with a
    parseable envelope) but is NOT a successful functional result.

    This carries the billable/audit material that must be persisted even
    when the PromptRun is marked FAILED:

    - provider_request_id / provider_response_id: identifiers returned by
      the provider for support/accounting traceability.
    - returned_model: the model the provider actually used (may differ from
      requested_model).
    - usage: normalized token counts (input, output, cached, reasoning,
      search_requests, etc.).  None fields mean the provider did not
      report them — never invent values.
    - citations: sources returned by the provider (preserved for audit even
      on failure).
    - latency_ms: measured round-trip latency.
    - search_used: whether any web_search_call was observed.
    - incomplete_reason: sanitized reason string when the provider reports
      an incomplete response (e.g. "max_output_tokens").  None if the
      response was nominally complete but still empty/unusable.
    - max_tool_calls_violation: when the provider returned more
      web_search_call items (TOTAL, all action types) than the configured
      limit, this holds the observed total count.  None when no violation
      was detected.
    - requested_max_tool_calls: the max_tool_calls limit that was sent in
      the request to the provider.  None when the request did not include
      max_tool_calls (e.g. MODEL_ONLY mode).  This is essential for
      historical auditability — it allows proving what limit was in force
      at execution time, even if the configuration changes later.
    - observed_search_requests: LEGACY.  The raw TOTAL count of
      web_search_call items observed in the response (same value as
      usage.search_requests for OpenAI).  Kept for backward compatibility
      with historical rows and error messages.  New code should read
      observed_web_tool_call_count instead.
    - observed_web_tool_call_count: authoritative TOTAL count of
      web_search_call output items (all action types).  This is the value
      compared against requested_max_tool_calls.
    - search_action_count / open_page_action_count /
      find_in_page_action_count / unknown_web_action_count: per-action
      breakdown of observed_web_tool_call_count (mirrors usage.*).

    IMPORTANT:
    - This object MUST NOT contain API keys, Authorization headers, or
      raw response bodies.
    - It MUST NOT contain chain-of-thought/reasoning text.
    - It is distinct from ProviderResult: ProviderResult represents a
      SUCCEEDED execution; ProviderFailureEvidence represents a FAILED
      execution that still has billable evidence.
    """

    provider: LLMProvider
    surface: ProviderSurface
    execution_mode: ProviderExecutionMode
    requested_model: str
    returned_model: str | None
    provider_request_id: str | None
    provider_response_id: str | None
    usage: ProviderUsage
    citations: tuple[ProviderCitation, ...]
    latency_ms: int
    search_used: bool
    incomplete_reason: str | None = None
    max_tool_calls_violation: int | None = None
    requested_max_tool_calls: int | None = None
    observed_search_requests: int | None = None
    observed_web_tool_call_count: int | None = None
    search_action_count: int | None = None
    open_page_action_count: int | None = None
    find_in_page_action_count: int | None = None
    unknown_web_action_count: int | None = None


@runtime_checkable
class ProviderAdapter(Protocol):
    """Protocol for provider adapters.

    Adapters are async infrastructure services. They:
    - Execute exactly ONE provider request per execute() call
    - Do NOT automatically retry
    - Do NOT call quota/usage services
    - Do NOT persist anything
    - Do NOT couple to FastAPI or SQLAlchemy
    """

    provider: LLMProvider
    surface: ProviderSurface

    def capabilities(self) -> ProviderCapabilities: ...

    async def execute(self, request: ProviderRequest) -> ProviderResult: ...
